### ISSUE TITLE
Include an async sample in the starter template

### ISSUE THREAD

**Issue by glennblock** [auth0/slash#1]
Currently the hello world created when you do `/wt create` returns a result synchronously. This is fine for a hello world, but several users (@ParidelPooya) have complained that when they add io / calling out to servers, the slash command times out. 

The proper way to handle this is to return a result immediately and then use the postback URL to send a result in the future when the task has finished.

We should add a comment with an inline example or pointing to one. The example could be something simple like the [curl] (https://gist.github.com/glennblock/290d84a3741fc5829a28a56863bc9a3e) task.

**Comment by tjanczuk** [comment]
With the release of Slash Webtasks 1.2.0 the timeout issue is largely mitigated, so an async sample is not as vital as before. Having said it was added to the docs: https://github.com/auth0/slash#sending-responses
