### ISSUE TITLE
Message attachments causing message to not send

### ISSUE THREAD

**Issue by laurenraddatz** [auth0/slash#3]
1. Version: 2.0.2, Team ID: T041VBS4X, User ID: U1NRUBTNF
2. /wt np laurenisacat
4. expected result (result given in the runner as well):
```{
  "response_type": "in_channel",
  "attachments": [
    {
      "text": "*laurenisacat* is currently listening to:",
      "thumb_url": "https://lastfm-img2.akamaized.net/i/u/174s/476f43537cd1b652f8502d4a49165e0a.png",
      "fields": [
        {
          "title": "Artist",
          "value": "JPEGMAFIA",
          "short": true
        },
        {
          "title": "Title",
          "value": "Real Nega",
          "short": true
        },
        {
          "title": "Stream",
          "value": "<https://play.spotify.com/track/3HsOlSmTjiUmwJLrrNutDR|Listen on Spotify...>",
          "short": false
        }
      ],
      "mrkdwn_in": [
        "text"
      ]
    }
  ]
}
```
actual: no response in channel

I have been testing with our other webtasks, and only the ones without attachments seem to be posting back to Slack. The other ones do not. Everything works as expected in the runner, though.

**Comment by NotMyself** [comment]
Hi @laurenraddatz,

Very sorry about how long it took to reply to this issue. I took a look at your example above and wrote a quick test case. It appears that your slack message is missing the `text` property. If I add the property to the message you posted above I get output in Slack. It looks like it is required.

**Comment by laurenraddatz** [comment]
thanks! the documentation hadn't been updated to reflect this requirement at the time of posting.
